CREATE EXTENSION unaccent;

CREATE TABLE Leagues (
League VARCHAR(255),
PRIMARY KEY(League)
);

INSERT INTO Leagues (League) VALUES 
( 'Argentina Primera División' ),
( 'Australian Hyundai A-League' ),
( 'Austrian Football Bundesliga' ),
( 'Belgian Jupiler Pro League' ),
( 'Campeonato Brasileiro Série A' ),
( 'Chilian Campeonato Nacional' ),
( 'Chinese Super League' ),
( 'Colombian Liga Postobón' ),
( 'Danish Superliga' ),
( 'English League Championship' ),
( 'English League One' ),
( 'English League Two' ),
( 'English Premier League' ),
( 'French Ligue 1' ),
( 'French Ligue 2' ),
( 'German 1. Bundesliga' ),
( 'German 2. Bundesliga' ),
( 'German 3. Bundesliga' ),
( 'Holland Eredivisie' ),
( 'Italian Serie A' ),
( 'Italian Serie B' ),
( 'Japanese J. League Division 1' ),
( 'Korean K League Classic' ),
( 'Mexican Liga MX' ),
( 'Norwegian Eliteserien' ),
( 'Polish T-Mobile Ekstraklasa' ),
( 'Portuguese Liga ZON SAGRES' ),
( 'Rep. Ireland Airtricity League' ),
( 'Rest of World' ),
( 'Saudi Abdul L. Jameel League' ),
( 'Scottish Premiership' ),
( 'Spain Primera Division' ),
( 'Spanish Segunda División' ),
( 'Swedish Allsvenskan' ),
( 'Swiss Super League' ),
( 'Turkish Süper Lig' ),
( 'USA Major League Soccer' )